services:
  db:
    image: postgres
    container_name: homecooked
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
       - "5432:5432"
    volumes:
       - ./specs/food_menu_system/database/database_schema.sql:/docker-entrypoint-initdb.d/init.sql
