package fooditem

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/pareshvernekar/homecooked/internal/errors"
	logger "github.com/pareshvernekar/homecooked/internal/logger"
	models "github.com/pareshvernekar/homecooked/internal/models"
	validation "github.com/pareshvernekar/homecooked/internal/validation"
)

type FoodItemRepository interface {
	ListByTenant(ctx context.Context, tenantID string, page, limit int) ([]*models.FoodItem, int64, error)
	GetByID(ctx context.Context, tenantID string, id string) (*models.FoodItem, error)
	Create(ctx context.Context, item *models.FoodItem) error
	Update(ctx context.Context, item *models.FoodItem) error
	Delete(ctx context.Context, id string) (int64, error)
}

type FoodCategoryService interface {
	GetCategoryByName(ctx context.Context, name string, tenantID string) (*models.FoodCategory, error)
}

// FoodItemService handles food item business logic with caching support.
type FoodItemService struct {
	repository      FoodItemRepository
	logger          *logger.Logger
	categoryService FoodCategoryService
}

// NewFoodItemService creates a new instance with dependency injection.
func NewFoodItemService(
	repo FoodItemRepository,
	l *logger.Logger,
	catSvc FoodCategoryService,
) *FoodItemService {
	return &FoodItemService{
		repository:      repo,
		logger:          l,
		categoryService: catSvc,
	}
}

// ValidateFoodItemUpdate validates a food item update request.
func (s *FoodItemService) ValidateFoodItemUpdate(updateReq *models.FoodItemUpdateRequest) error {
	if err := validation.ValidateFoodItemUpdate(updateReq); err != nil {
		return err
	}
	return nil
}

// Create creates a new food item for the current tenant.
func (s *FoodItemService) Create(ctx context.Context, createReq *models.FoodItemCreateRequest, tenantID string) (*models.FoodItem, error) {
	s.logger.Info(ctx, "Creating food item", "tenant_id", tenantID, "name", createReq.Name)

	// Validate request payload - returns ValidationError (HTTP 400)
	if err := validation.ValidateFoodItemCreate(createReq); err != nil {
		return nil, errors.CreateValidationError(
			fmt.Sprintf("Validation failed for food item '%s': %s", createReq.Name, err.Error()),
			map[string]interface{}{
				"field": "unknown",
			},
		)
	}

	now := time.Now().UTC().UnixMilli()

	// Resolve category name to ID using category service
	if s.categoryService == nil {
		return nil, errors.CreateServiceInitializationError(
			"Category service dependency not initialized for food item creation",
			nil,
			tenantID,
		)
	}

	category, err := s.categoryService.GetCategoryByName(ctx, createReq.CategoryName, tenantID)
	if err != nil {
		return nil, errors.CreateDatabaseError(
			fmt.Sprintf("Failed to resolve category name '%s' for tenant %s", createReq.CategoryName, tenantID),
			err,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Category name resolved to ID",
		"category_name", createReq.CategoryName,
		"category_id", category.ID,
		"tenant_id", tenantID)

	// Build food item entity with resolved category ID - convert pointer fields appropriately
	foodItem := &models.FoodItem{
		ID:                 "", // Generated by database via UUID extension
		TenantID:           tenantID,
		Name:               createReq.Name,
		Description:        createReq.Description,
		CategoryID:         category.ID,
		Price:              createReq.Price,
		ImageURL:           createReq.ImageURL,
		Avoidance:          createReq.Avoidance,
		IsVegetarian:       isBoolPtr(createReq.IsVegetarian, false),
		AvailabilityStatus: resolveAvailabilityStatus(createReq.AvailabilityStatus),
		CreatedAt:          now,
		UpdatedAt:          now,
	}

	// Persist to database - returns DatabaseError (HTTP 500)
	if err := s.repository.Create(ctx, foodItem); err != nil {
		return nil, errors.CreateDatabaseError(
			fmt.Sprintf("Database error creating food item '%s': %s", foodItem.Name, errors.SanitizeErrorMessage(err)),
			err,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Food item persisted to database",
		"food_item_id", foodItem.ID,
		"food_item_name", foodItem.Name)
	return foodItem, nil
}

// GetByID retrieves a single food item by its ID with cache support.
func (s *FoodItemService) GetByID(ctx context.Context, id string, tenantID string) (*models.FoodItem, error) {
	s.logger.Info(ctx, "GetFoodItemByID: Fetching food item by ID",
		"food_item_id", id,
		"tenant_id", tenantID)

	// Step 1: Attempt to load from cache if cache client is available	// Step 2: No cache - load from database
	dbItem, err := s.repository.GetByID(ctx, tenantID, id)
	if err != nil {
		return nil, errors.CreateDatabaseError(
			fmt.Sprintf("Failed to retrieve food item '%s' from database", id),
			err,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Successfully retrieved food item from database",
		"food_item_id", dbItem.ID)
	return dbItem, nil
}

// List retrieves all food items for a specific tenant.
func (s *FoodItemService) List(ctx context.Context, tenantID string, page, limit int) ([]*models.FoodItem, error) {
	s.logger.Info(ctx, "List: Fetching food items for tenant",
		"tenant_id", tenantID,
		"page", page,
		"limit", limit)

	// Retrieve from database with tenant isolation (RLS handles filtering)
	items, total, err := s.repository.ListByTenant(ctx, tenantID, page, limit)
	if err != nil {
		s.logger.Error(ctx, "List: Failed to retrieve food items from database",
			"tenant_id", tenantID,
			"error", errors.SanitizeErrorMessage(err))

		return nil, errors.CreateDatabaseError(
			fmt.Sprintf("Failed to list food items for tenant %s: %s", tenantID, errors.SanitizeErrorMessage(err)),
			err,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Successfully retrieved food items from database",
		"tenant_id", tenantID,
		"page", page,
		"limit", limit,
		"count", total)
	return items, nil
}

// Update updates an existing food item.
func (s *FoodItemService) Update(ctx context.Context, id string, updateReq *models.FoodItemUpdateRequest, tenantID string) error {
	s.logger.Info(ctx, "Updating food item",
		"food_item_id", id,
		"tenant_id", tenantID)

	// Step 1: Validate input - returns ValidationError (HTTP 400)
	if err := s.ValidateFoodItemUpdate(updateReq); err != nil {
		return errors.CreateValidationError(
			fmt.Sprintf("Validation failed for update request targeting food item '%s': %s", id, err.Error()),
			map[string]interface{}{
				"food_item_id": id,
				"tenant_id":    tenantID,
			},
		)
	}

	// Step 2: Verify item exists and belongs to tenant
	dbItem, err := s.repository.GetByID(ctx, tenantID, id)
	if err != nil {
		return errors.CreateDatabaseError(
			fmt.Sprintf("Failed to verify food item '%s' for tenant %s", id, tenantID),
			err,
			tenantID,
		)
	}

	if dbItem == nil {
		return errors.CreateNotFoundError(
			fmt.Sprintf("Food item '%s' not found for tenant %s", id, tenantID),
			id,
			tenantID,
		)
	}

	// Step 3: Check if item belongs to this tenant (ForbiddenError - HTTP 403)
	if dbItem.TenantID != tenantID {
		return errors.CreateForbiddenError(
			fmt.Sprintf("Cannot update food item '%s' - it does not belong to tenant %s", id, tenantID),
			id,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Verified item belongs to tenant",
		"food_item_id", id,
		"food_item_tenant_id", dbItem.TenantID)

	category, err := s.categoryService.GetCategoryByName(ctx, updateReq.CategoryName, tenantID)
	if err != nil {
		return errors.CreateDatabaseError(
			fmt.Sprintf("Failed to resolve category name '%s' for tenant %s", updateReq.CategoryName, tenantID),
			err,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Category name resolved to ID",
		"category_name", updateReq.CategoryName,
		"category_id", category.ID,
		"tenant_id", tenantID)

	// Build updated food item entity with resolved category ID - convert pointer fields appropriately
	updatedItem := &models.FoodItem{
		ID:                 id,
		TenantID:           tenantID,
		Name:               updateReq.Name,
		Description:        updateReq.Description,
		CategoryID:         category.ID,
		Price:              updateReq.Price,
		ImageURL:           updateReq.ImageURL,
		Avoidance:          updateReq.Avoidance,
		IsVegetarian:       isBoolPtr(updateReq.IsVegetarian, dbItem.IsVegetarian),
		AvailabilityStatus: resolveAvailabilityStatus(updateReq.AvailabilityStatus),
		CreatedAt:          dbItem.CreatedAt,
		UpdatedAt:          time.Now().UTC().UnixMilli(),
	}

	// Step 4: Update database - returns DatabaseError (HTTP 500)
	if err := s.repository.Update(ctx, updatedItem); err != nil {
		return errors.CreateDatabaseError(
			fmt.Sprintf("Database error updating food item '%s': %s", id, errors.SanitizeErrorMessage(err)),
			err,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Successfully updated food item in database",
		"food_item_id", id,
		"updated_fields", updateReq)

	return nil
}

// Delete removes a food item from the database.
func (s *FoodItemService) Delete(ctx context.Context, id string, tenantID string) (int64, error) {
	s.logger.Info(ctx, "Deleting food item",
		"food_item_id", id,
		"tenant_id", tenantID)

	// Step 1: Verify item exists and belongs to tenant (returns ForbiddenError - HTTP 403)
	dbItem, err := s.repository.GetByID(ctx, tenantID, id)
	if err != nil {
		return 0, errors.CreateDatabaseError(
			fmt.Sprintf("Failed to verify food item '%s' for tenant %s", id, tenantID),
			err,
			tenantID,
		)
	}

	if dbItem == nil {
		return 0, errors.CreateNotFoundError(
			fmt.Sprintf("Food item '%s' not found for tenant %s", id, tenantID),
			id,
			tenantID,
		)
	}

	// Step 2: Check if item belongs to this tenant (ForbiddenError - HTTP 403)
	if dbItem.TenantID != tenantID {
		return 0, errors.CreateForbiddenError(
			fmt.Sprintf("Cannot delete food item '%s' - it does not belong to tenant %s", id, tenantID),
			id,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Verified item belongs to tenant before deletion",
		"food_item_id", id,
		"food_item_tenant_id", dbItem.TenantID)
	rowsAffected, err := s.repository.Delete(ctx, id)
	// Step 3: Delete from database
	if err != nil {
		return 0, errors.CreateDatabaseError(
			fmt.Sprintf("Failed to delete food item '%s' from database", id),
			err,
			tenantID,
		)
	}

	s.logger.Info(ctx, "Successfully deleted food item from database",
		"food_item_id", id)

	return rowsAffected, nil
}

// resolveAvailabilityStatus normalizes availability status strings to canonical values
func resolveAvailabilityStatus(status string) string {
	status = strings.ToLower(strings.TrimSpace(status))
	switch status {
	case "available", "A", "a", "normal":
		return "available"
	case "unavailable", "U", "u", "out_of_stock":
		return "unavailable"
	case "low_stock", "L", "l", "limited":
		return "low_stock"
	default:
		return "available" // Default to available if unknown status
	}
}

// isBoolPtr converts a pointer to bool or returns the default value if nil
func isBoolPtr(ptr *bool, defaultVal bool) bool {
	if ptr == nil {
		return defaultVal
	}
	return *ptr
}
